// examples/with-nuxt/app/components/Thread.vue
<script setup lang="ts">
import {
  AuiIf,
  ComposerPrimitiveCancel,
  ComposerPrimitiveInput,
  ComposerPrimitiveSend,
  SuggestionPrimitiveDescription,
  SuggestionPrimitiveTitle,
  SuggestionPrimitiveTrigger,
  ThreadPrimitiveMessages,
  ThreadPrimitiveScrollToBottom,
  ThreadPrimitiveSuggestions,
  ThreadPrimitiveViewport,
} from "@assistant-ui/vue";
import type {} from "@assistant-ui/core/store";
import { ArrowDownIcon, ArrowUpIcon, SquareIcon } from "@lucide/vue";
</script>

<template>
  <div class="flex h-full min-w-0 flex-1 flex-col">
    <ThreadPrimitiveViewport
      class="relative flex flex-1 flex-col overflow-x-auto overflow-y-scroll scroll-smooth"
    >
      <div class="mx-auto flex w-full max-w-2xl flex-1 flex-col px-4 pt-12">
        <AuiIf :condition="(s) => s.thread.messages.length === 0">
          <div
            class="flex flex-1 flex-col items-center justify-center gap-6 pb-24"
          >
            <h1 class="text-2xl font-semibold">How can I help you today?</h1>
            <div
              class="flex flex-wrap items-center justify-center gap-2 px-4"
            >
              <ThreadPrimitiveSuggestions>
                <SuggestionPrimitiveTrigger
                  send
                  class="text-foreground hover:bg-muted border-border/60 flex h-auto flex-col items-start gap-0.5 rounded-2xl border px-3.5 py-2 text-sm transition-colors"
                >
                  <span class="font-medium"
                    ><SuggestionPrimitiveTitle
                  /></span>
                  <span class="text-muted-foreground text-xs">
                    <SuggestionPrimitiveDescription />
                  </span>
                </SuggestionPrimitiveTrigger>
              </ThreadPrimitiveSuggestions>
            </div>
          </div>
        </AuiIf>
        <ol class="mb-4 flex flex-col gap-y-6 empty:hidden">
          <ThreadPrimitiveMessages>
            <Message />
          </ThreadPrimitiveMessages>
        </ol>
        <ThreadPrimitiveScrollToBottom
          class="border-border/60 bg-background sticky bottom-2 z-10 mx-auto rounded-full border p-2 shadow-sm transition-[opacity,visibility] disabled:invisible disabled:opacity-0"
          aria-label="Scroll to bottom"
        >
          <ArrowDownIcon class="size-4" />
        </ThreadPrimitiveScrollToBottom>
      </div>
    </ThreadPrimitiveViewport>
    <div class="mx-auto w-full max-w-2xl px-4 pb-4">
      <div
        class="border-border/60 focus-within:border-border flex w-full flex-col gap-2 rounded-2xl border p-2.5 shadow-[0_4px_16px_-8px_rgba(0,0,0,0.08),0_1px_2px_rgba(0,0,0,0.04)] transition-[border-color,box-shadow] focus-within:shadow-[0_6px_24px_-8px_rgba(0,0,0,0.12),0_1px_2px_rgba(0,0,0,0.05)]"
      >
        <ComposerPrimitiveInput
          class="caret-primary placeholder:text-muted-foreground/80 max-h-32 min-h-10 w-full resize-none bg-transparent px-2.5 py-1 text-base outline-none"
          placeholder="Send a message..."
          rows="1"
        />
        <div class="flex items-center justify-end">
          <AuiIf :condition="(s) => !s.thread.isRunning">
            <ComposerPrimitiveSend
              class="bg-primary text-primary-foreground flex size-7 items-center justify-center rounded-full transition-opacity disabled:opacity-50"
              aria-label="Send"
            >
              <ArrowUpIcon class="size-4.5" />
            </ComposerPrimitiveSend>
          </AuiIf>
          <AuiIf :condition="(s) => s.thread.isRunning">
            <ComposerPrimitiveCancel
              class="bg-primary text-primary-foreground flex size-7 items-center justify-center rounded-full"
              aria-label="Stop"
            >
              <SquareIcon class="size-3.5 fill-current" />
            </ComposerPrimitiveCancel>
          </AuiIf>
        </div>
      </div>
    </div>
  </div>
</template>

// apps/docs/lib/xulux/learn/courses/build-generative-ui-assistant/stages/S2/project/components/assistant-ui/thread.tsx
"use client";

import {
  AuiIf,
  ComposerPrimitive,
  MessagePrimitive,
  ThreadPrimitive,
} from "@assistant-ui/react";
import { ArrowUp, CloudSun, Code2, PencilLine, Square } from "lucide-react";

const suggestions = [
  {
    label: "Weather",
    prompt: "What's the weather in San Francisco?",
    icon: CloudSun,
  },
  {
    label: "Code",
    prompt: "Explain React hooks like useState and useEffect.",
    icon: Code2,
  },
  {
    label: "Write",
    prompt: "Draft a short product announcement for a new dark mode.",
    icon: PencilLine,
  },
];

export function Thread() {
  return (
    <ThreadPrimitive.Root className="flex h-full min-w-0 flex-col">
      <header className="border-b border-[var(--border)] px-5 py-4">
        <p className="font-medium">Generative UI Assistant</p>
        <p className="text-sm text-[var(--muted-foreground)]">
          Built with assistant-ui
        </p>
      </header>

      <ThreadPrimitive.Viewport className="flex min-w-0 flex-1 flex-col overflow-y-auto">
        <ThreadPrimitive.Empty>
          <div className="flex flex-1 items-center justify-center p-6 text-center">
            <div className="w-full max-w-2xl">
              <h1 className="text-2xl font-semibold">
                How can I help you today?
              </h1>
              <p className="mt-2 text-[var(--muted-foreground)]">
                Choose a starting point or ask anything.
              </p>
              <div className="mt-6 grid gap-2 sm:grid-cols-3">
                {suggestions.map(({ label, prompt, icon: Icon }) => (
                  <ThreadPrimitive.Suggestion
                    key={label}
                    prompt={prompt}
                    asChild
                  >
                    <button className="flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--background)] px-4 py-3 text-left text-sm hover:bg-[var(--muted)]">
                      <Icon className="size-4 text-[var(--muted-foreground)]" />
                      {label}
                    </button>
                  </ThreadPrimitive.Suggestion>
                ))}
              </div>
            </div>
          </div>
        </ThreadPrimitive.Empty>

        <ThreadPrimitive.Messages
          components={{ UserMessage, AssistantMessage }}
        />

        <ThreadPrimitive.ViewportFooter className="sticky bottom-0 mt-auto w-full bg-[var(--background)] p-4">
          <ComposerPrimitive.Root className="mx-auto flex w-full max-w-2xl items-end gap-2 rounded-2xl border border-[var(--border)] bg-[var(--muted)] p-2">
            <ComposerPrimitive.Input asChild>
              <textarea
                aria-label="Message"
                placeholder="Ask anything..."
                rows={1}
                className="field-sizing-content max-h-32 min-h-10 min-w-0 flex-1 resize-none bg-transparent px-3 py-2 outline-none"
              />
            </ComposerPrimitive.Input>
            <AuiIf condition={(state) => !state.thread.isRunning}>
              <ComposerPrimitive.Send className="flex size-10 items-center justify-center rounded-xl bg-[var(--foreground)] text-[var(--background)] disabled:opacity-40">
                <ArrowUp className="size-4" />
                <span className="sr-only">Send message</span>
              </ComposerPrimitive.Send>
            </AuiIf>
            <AuiIf condition={(state) => state.thread.isRunning}>
              <ComposerPrimitive.Cancel className="flex size-10 items-center justify-center rounded-xl bg-[var(--foreground)] text-[var(--background)]">
                <Square className="size-3.5" fill="currentColor" />
                <span className="sr-only">Stop generating</span>
              </ComposerPrimitive.Cancel>
            </AuiIf>
          </ComposerPrimitive.Root>
        </ThreadPrimitive.ViewportFooter>
      </ThreadPrimitive.Viewport>
    </ThreadPrimitive.Root>
  );
}

function UserMessage() {
  return (
    <MessagePrimitive.Root className="mx-auto flex w-full max-w-2xl justify-end px-4 py-2">
      <div className="max-w-[80%] rounded-2xl bg-[var(--muted)] px-4 py-3">
        <MessagePrimitive.Content />
      </div>
    </MessagePrimitive.Root>
  );
}

function AssistantMessage() {
  return (
    <MessagePrimitive.Root className="mx-auto w-full max-w-2xl px-4 py-3 leading-7">
      <MessagePrimitive.Content />
    </MessagePrimitive.Root>
  );
}
