// packages/ui/src/components/react-native/assistant-ui/elements/tool-fallback.tsx
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import {
  toolApprovalAcceptsText,
  useAuiState,
  type ToolApprovalAnswer,
  type ToolApprovalOption,
  type ToolApprovalQuestion,
  type ToolCallMessagePart,
  type ToolCallMessagePartComponent,
  type ToolCallMessagePartProps,
  type ToolCallMessagePartStatus,
} from "@assistant-ui/react-native";
import { WrenchIcon } from "lucide-react-native";
import { type FC, useState } from "react";
import { Platform, Pressable, Text, TextInput, View } from "react-native";
import {
  field,
  inkButton,
  mono,
  monoStyle,
  textButtonHitSlop,
  useAnnounce,
  useHydrated,
  webLiveRegion,
} from "./surfaces";
import { formatUnknownValue } from "../utils/task";

const APPROVED_RESULT = "Approved by user";
const DENIED_RESULT = "User denied tool execution";

const APPROVAL_OPTION_DEFAULT_LABELS: Record<string, string> = {
  "allow-once": "Allow",
  "allow-always": "Always allow",
  "reject-once": "Deny",
  "reject-always": "Always deny",
};

const isKnownKind = (kind: string) =>
  Object.hasOwn(APPROVAL_OPTION_DEFAULT_LABELS, kind);

const isAllowKind = (kind: string) =>
  kind === "allow-once" || kind === "allow-always";

const approvalOptionLabel = (option: ToolApprovalOption) =>
  option.label ??
  (isKnownKind(option.kind)
    ? APPROVAL_OPTION_DEFAULT_LABELS[option.kind]
    : undefined) ??
  option.id;

const isQuestion = (approval: ToolCallMessagePart["approval"]) =>
  approval?.display === "select" ||
  approval?.display === "text" ||
  approval?.display === "questions";

const questionAcceptsText = (question: ToolApprovalQuestion) =>
  !question.options?.length || question.allowFreeform === true;

const answerLabels = (
  question: ToolApprovalQuestion,
  answer: ToolApprovalAnswer | undefined,
) => [
  ...(answer?.optionIds ?? []).map(
    (id) => question.options?.find((option) => option.id === id)?.label ?? id,
  ),
  ...(answer?.text?.trim() ? [answer.text] : []),
];

const isSettled = (approval: ToolCallMessagePart["approval"]) =>
  approval != null &&
  (approval.approved !== undefined || approval.resolution !== undefined);

/**
 * A settled request reads as a past-tense record of what happened to it, so
 * scrolling back never shows a live control for a decision already made.
 */
const approvalReceipt = (
  approval: NonNullable<ToolCallMessagePart["approval"]>,
) => {
  if (approval.resolution !== undefined)
    return {
      label:
        approval.resolution === "cancelled"
          ? "Cancelled before a decision"
          : "Expired before a decision",
      option: undefined,
    };

  const chosen =
    approval.optionId === undefined
      ? undefined
      : approval.options?.find((option) => option.id === approval.optionId);
  const answered =
    isQuestion(approval) || (chosen !== undefined && !isKnownKind(chosen.kind));
  const verb = approval.approved
    ? answered
      ? "Answered"
      : "Allowed"
    : answered
      ? "Dismissed"
      : "Denied";

  return {
    label: `${verb}${approval.isAutomatic ? " automatically" : ""}`,
    option:
      chosen !== undefined ? approvalOptionLabel(chosen) : approval.optionId,
  };
};

const ToolFallbackApprovalReceipt: FC<{
  approval: NonNullable<ToolCallMessagePart["approval"]>;
  className?: string;
}> = ({ approval, className }) => {
  const receipt = approvalReceipt(approval);
  const notes = [
    ...new Set(
      [approval.text, approval.reason].filter(
        (value): value is string => typeof value === "string" && value !== "",
      ),
    ),
  ];

  return (
    <View className={cn("aui-tool-fallback-approval-receipt gap-1", className)}>
      {approval.prompt ? (
        <Text className="aui-tool-fallback-approval-prompt text-muted-foreground text-sm">
          {approval.prompt}
        </Text>
      ) : null}
      <Text className="aui-tool-fallback-approval-receipt-label text-foreground text-sm font-medium">
        {receipt.label}
        {receipt.option !== undefined ? (
          <Text className="text-muted-foreground font-normal">
            {` · ${receipt.option}`}
          </Text>
        ) : null}
      </Text>
      {approval.answers &&
        approval.questions?.map((question) => {
          const labels = answerLabels(
            question,
            approval.answers && Object.hasOwn(approval.answers, question.id)
              ? approval.answers[question.id]
              : undefined,
          );
          if (labels.length === 0) return null;
          return (
            <Text
              key={question.id}
              className="aui-tool-fallback-approval-receipt-answer text-foreground text-sm"
            >
              <Text className="text-muted-foreground">
                {question.header ?? question.prompt}
              </Text>
              {` · ${labels.join(", ")}`}
            </Text>
          );
        })}
      {notes.map((text) => (
        <Text
          key={text}
          className="aui-tool-fallback-approval-receipt-note text-muted-foreground text-sm"
        >
          {text}
        </Text>
      ))}
    </View>
  );
};

export const offersInterruptAction = (
  status: ToolCallMessagePartStatus | undefined,
  approval: ToolCallMessagePart["approval"],
  interrupt: ToolCallMessagePart["interrupt"],
) =>
  status?.type !== "requires-action" ||
  status.reason !== "interrupt" ||
  approval != null ||
  interrupt != null;

const ApprovalButton: FC<{
  label: string;
  primary?: boolean;
  pressed?: boolean;
  disabled: boolean;
  onPress: () => void;
}> = ({ label, primary = false, pressed, disabled, onPress }) => (
  <Pressable
    onPress={onPress}
    disabled={disabled}
    accessibilityRole="button"
    accessibilityLabel={label}
    {...(pressed !== undefined &&
      (Platform.OS === "web"
        ? { "aria-pressed": pressed }
        : { "aria-selected": pressed }))}
    hitSlop={textButtonHitSlop}
    className={cn(
      "h-8 justify-center rounded-full px-3.5 disabled:opacity-50",
      primary ? inkButton : "border-border/60 active:bg-foreground/5 border",
    )}
  >
    <Text
      className={cn(
        "text-xs font-medium",
        primary ? "text-background" : "text-foreground",
      )}
    >
      {label}
    </Text>
  </Pressable>
);

const ToolFallbackApprovalQuestions: FC<{
  questions: readonly ToolApprovalQuestion[];
  dismissible: boolean;
  disabled: boolean;
  onSend: (answers: Record<string, ToolApprovalAnswer>) => void;
  onDismiss: () => void;
}> = ({ questions, dismissible, disabled, onSend, onDismiss }) => {
  const hydrated = useHydrated();
  const [selected, setSelected] = useState<
    ReadonlyMap<string, readonly string[]>
  >(() => new Map());
  const [typed, setTyped] = useState<ReadonlyMap<string, string>>(
    () => new Map(),
  );

  const toggle = (question: ToolApprovalQuestion, optionId: string) =>
    setSelected((current) => {
      const chosen = current.get(question.id) ?? [];
      const next = chosen.includes(optionId)
        ? chosen.filter((id) => id !== optionId)
        : question.multiple
          ? [...chosen, optionId]
          : [optionId];
      return new Map(current).set(question.id, next);
    });

  const answerOf = (question: ToolApprovalQuestion): ToolApprovalAnswer => {
    const optionIds = selected.get(question.id) ?? [];
    const draft = typed.get(question.id);
    const text = draft?.trim() ? draft : undefined;
    return {
      ...(optionIds.length > 0 && { optionIds }),
      ...(text !== undefined && { text }),
    };
  };

  const complete =
    questions.length > 0 &&
    questions.every((question) => {
      const answer = answerOf(question);
      return answer.optionIds !== undefined || answer.text !== undefined;
    });

  return (
    <>
      {questions.map((question) => {
        const chosen = selected.get(question.id) ?? [];
        return (
          <View
            key={question.id}
            accessibilityLabel={question.prompt}
            className="aui-tool-fallback-approval-question gap-2"
          >
            <Text className="aui-tool-fallback-approval-question-prompt text-foreground text-sm">
              {question.header ? (
                <Text className="text-muted-foreground text-xs font-medium uppercase">
                  {`${question.header}  `}
                </Text>
              ) : null}
              {question.prompt}
            </Text>
            {question.options && question.options.length > 0 ? (
              <View className="flex-row flex-wrap items-center gap-2">
                {question.options.map((option) => (
                  <ApprovalButton
                    key={option.id}
                    label={option.label}
                    primary={chosen.includes(option.id)}
                    pressed={chosen.includes(option.id)}
                    disabled={disabled}
                    onPress={() => toggle(question, option.id)}
                  />
                ))}
              </View>
            ) : null}
            {question.options?.some((option) => option.description) ? (
              <View className="gap-0.5">
                {question.options.map((option) =>
                  option.description ? (
                    <Text
                      key={option.id}
                      className="text-muted-foreground text-xs"
                    >
                      {`${option.label}: ${option.description}`}
                    </Text>
                  ) : null,
                )}
              </View>
            ) : null}
            {questionAcceptsText(question) ? (
              <TextInput
                value={typed.get(question.id) ?? ""}
                onChangeText={(value) =>
                  setTyped((current) =>
                    new Map(current).set(question.id, value),
                  )
                }
                editable={!disabled}
                multiline
                textAlignVertical="top"
                accessibilityLabel={question.prompt}
                placeholder={
                  question.options?.length
                    ? "Or type an answer"
                    : "Type your answer"
                }
                placeholderTextColorClassName={
                  hydrated ? "accent-muted-foreground/60" : undefined
                }
                className={cn(
                  "text-foreground web:resize-none web:outline-none min-h-16 rounded-lg px-2.5 py-2 text-sm",
                  field,
                )}
              />
            ) : null}
          </View>
        );
      })}
      <View className="flex-row flex-wrap items-center gap-2">
        <ApprovalButton
          label="Send"
          primary
          disabled={disabled || !complete}
          onPress={() => {
            if (disabled || !complete) return;
            onSend(
              Object.fromEntries(
                questions.map((question) => [question.id, answerOf(question)]),
              ),
            );
          }}
        />
        {dismissible ? (
          <ApprovalButton
            label="Dismiss"
            disabled={disabled}
            onPress={onDismiss}
          />
        ) : null}
      </View>
    </>
  );
};

export const ToolFallbackApproval: FC<
  Partial<
    Pick<
      ToolCallMessagePartProps,
      "addResult" | "resume" | "respondToApproval" | "status"
    >
  > & {
    interrupt?: ToolCallMessagePart["interrupt"];
    approval?: ToolCallMessagePart["approval"];
    argsText?: string;
    className?: string;
  }
> = ({
  addResult,
  resume,
  interrupt,
  approval,
  respondToApproval,
  status,
  argsText,
  className,
}) => {
  const hydrated = useHydrated();
  const canAnswer = useAuiState(
    (s) => s.optional.thread?.capabilities.answerToolCall !== false,
  );
  const [submitted, setSubmitted] = useState(false);
  const [confirmingId, setConfirmingId] = useState<string | null>(null);
  const [answer, setAnswer] = useState("");
  const [error, setError] = useState<string | null>(null);
  useAnnounce(error ?? undefined);

  if (approval != null && isSettled(approval))
    return (
      <ToolFallbackApprovalReceipt approval={approval} className={className} />
    );

  if (!offersInterruptAction(status, approval, interrupt)) return null;

  const promptText = approval?.prompt ? (
    <Text className="aui-tool-fallback-approval-prompt text-foreground text-sm">
      {approval.prompt}
    </Text>
  ) : null;

  if (!canAnswer)
    return promptText ? (
      <View className={cn("aui-tool-fallback-approval gap-2", className)}>
        {promptText}
      </View>
    ) : null;

  // A declared option list is a host constraint: the kit never adds an
  // approval path beyond it, and keeps a refusal path only for an action.
  const declaredOptions = respondToApproval ? approval?.options : undefined;
  const acceptsText =
    approval != null &&
    respondToApproval != null &&
    toolApprovalAcceptsText(approval);

  const submit = (send: () => Promise<void> | void) => {
    setSubmitted(true);
    setError(null);
    void (async () => {
      try {
        await send();
      } catch (sendError) {
        setSubmitted(false);
        setError(
          sendError instanceof Error ? sendError.message : String(sendError),
        );
      }
    })();
  };

  const typedNote = () => (answer.trim() ? { text: answer } : {});

  const respond = (approved: boolean) => {
    if (submitted) return;
    if (
      approval != null &&
      approval.approved === undefined &&
      respondToApproval
    ) {
      submit(() => respondToApproval({ approved, ...typedNote() }));
    } else if (interrupt) {
      submit(() => resume?.({ approved }));
    } else if (
      status?.type === "requires-action" &&
      status.reason === "interrupt"
    ) {
      return;
    } else {
      submit(() => addResult?.(approved ? APPROVED_RESULT : DENIED_RESULT));
    }
  };

  // A custom kind has no decision class for the runtime to derive, so picking
  // one resolves as approved.
  const respondWithOption = (option: ToolApprovalOption) => {
    if (submitted) return;
    setConfirmingId(null);
    submit(() =>
      respondToApproval?.(
        isKnownKind(option.kind)
          ? { optionId: option.id, ...typedNote() }
          : { optionId: option.id, approved: true, ...typedNote() },
      ),
    );
  };

  // An empty answer is sent as given; a host that cannot record one rejects
  // it, which reopens the controls.
  const submitAnswer = () => {
    if (submitted) return;
    submit(() => respondToApproval?.({ text: answer }));
  };

  const dismiss = () => {
    if (submitted) return;
    submit(() => respondToApproval?.({ approved: false }));
  };

  const handleOption = (option: ToolApprovalOption) => {
    if (option.confirm) {
      setConfirmingId(option.id);
    } else {
      respondWithOption(option);
    }
  };

  const confirming =
    confirmingId != null
      ? declaredOptions?.find((o) => o.id === confirmingId)
      : undefined;

  const question = isQuestion(approval);
  const dismissible =
    question && respondToApproval != null && approval?.dismissible === true;

  const dismissButton = dismissible ? (
    <ApprovalButton label="Dismiss" disabled={submitted} onPress={dismiss} />
  ) : null;

  const subject = argsText ? (
    <View
      className={cn(
        "aui-tool-fallback-approval-args rounded-lg px-2.5 py-2",
        field,
      )}
    >
      <Text className="text-foreground/70 text-xs" style={monoStyle} selectable>
        {argsText}
      </Text>
    </View>
  ) : null;

  const errorText = error ? (
    <Text
      accessibilityRole="alert"
      accessibilityLiveRegion={webLiveRegion}
      className="aui-tool-fallback-approval-error text-destructive text-xs"
    >
      {error}
    </Text>
  ) : null;

  const answerField = acceptsText ? (
    <View className="aui-tool-fallback-approval-answer gap-2">
      <TextInput
        value={answer}
        onChangeText={setAnswer}
        editable={!submitted}
        multiline
        textAlignVertical="top"
        accessibilityLabel={question ? (approval?.prompt ?? "Answer") : "Note"}
        placeholder={
          question ? "Type your answer" : "Add a note to your decision"
        }
        placeholderTextColorClassName={
          hydrated ? "accent-muted-foreground/60" : undefined
        }
        className={cn(
          "text-foreground web:resize-none web:outline-none min-h-16 rounded-lg px-2.5 py-2 text-sm",
          field,
        )}
      />
      {question && (
        <View className="flex-row flex-wrap items-center gap-2">
          <ApprovalButton
            label="Send"
            primary
            disabled={submitted}
            onPress={submitAnswer}
          />
          {dismissButton}
        </View>
      )}
    </View>
  ) : null;

  if (approval?.display === "questions" && respondToApproval) {
    return (
      <View className={cn("aui-tool-fallback-approval gap-3", className)}>
        {subject}
        {promptText}
        <ToolFallbackApprovalQuestions
          questions={approval.questions ?? []}
          dismissible={approval.dismissible === true}
          disabled={submitted}
          onSend={(answers) => submit(() => respondToApproval({ answers }))}
          onDismiss={dismiss}
        />
        {errorText}
      </View>
    );
  }

  if (confirming) {
    const confirmMeta =
      typeof confirming.confirm === "object" ? confirming.confirm : undefined;
    const confirmDescription =
      confirmMeta?.description ?? confirming.description;
    return (
      <View
        className={cn("aui-tool-fallback-approval-confirm gap-2", className)}
      >
        {subject}
        <Text className="text-foreground text-sm font-semibold">
          {confirmMeta?.title ?? `${approvalOptionLabel(confirming)}?`}
        </Text>
        {confirmDescription && (
          <Text className="text-muted-foreground text-sm">
            {confirmDescription}
          </Text>
        )}
        {confirming.grants && confirming.grants.length > 0 && (
          <View className="aui-tool-fallback-approval-confirm-grants items-start gap-1">
            {confirming.grants.map((grant) => (
              <View key={grant} className={cn("rounded px-1.5 py-0.5", field)}>
                <Text
                  className={cn(mono, "text-foreground")}
                  style={monoStyle}
                  selectable
                >
                  {grant}
                </Text>
              </View>
            ))}
          </View>
        )}
        <View className="flex-row flex-wrap items-center gap-2">
          <ApprovalButton
            label="Confirm"
            primary
            disabled={submitted}
            onPress={() => respondWithOption(confirming)}
          />
          <ApprovalButton
            label="Back"
            disabled={submitted}
            onPress={() => setConfirmingId(null)}
          />
        </View>
      </View>
    );
  }

  if (declaredOptions && declaredOptions.length > 0) {
    const allowOptions = declaredOptions.filter((o) => isAllowKind(o.kind));
    const customOptions = declaredOptions.filter((o) => !isKnownKind(o.kind));
    const rejectOptions = declaredOptions.filter(
      (o) => isKnownKind(o.kind) && !isAllowKind(o.kind),
    );
    return (
      <View className={cn("aui-tool-fallback-approval gap-2", className)}>
        {subject}
        {promptText}
        <View className="flex-row flex-wrap items-center gap-2">
          {[...allowOptions, ...customOptions, ...rejectOptions].map(
            (option) => (
              <ApprovalButton
                key={option.id}
                label={approvalOptionLabel(option)}
                primary={option === allowOptions[0]}
                disabled={submitted}
                onPress={() => handleOption(option)}
              />
            ),
          )}
          {rejectOptions.length === 0 && !question && (
            <ApprovalButton
              label="Deny"
              disabled={submitted}
              onPress={() => respond(false)}
            />
          )}
          {!acceptsText && dismissButton}
        </View>
        {answerField}
        {errorText}
      </View>
    );
  }

  // A question carries no decision to fabricate, so it renders only what the
  // request declared.
  if (question) {
    return (
      <View className={cn("aui-tool-fallback-approval gap-2", className)}>
        {subject}
        {promptText}
        {answerField}
        {!acceptsText && dismissButton && (
          <View className="flex-row flex-wrap items-center gap-2">
            {dismissButton}
          </View>
        )}
        {errorText}
      </View>
    );
  }

  return (
    <View className={cn("aui-tool-fallback-approval gap-2", className)}>
      {subject}
      {promptText}
      <View className="flex-row flex-wrap items-center gap-2">
        <ApprovalButton
          label="Allow"
          primary
          disabled={submitted}
          onPress={() => respond(true)}
        />
        <ApprovalButton
          label="Deny"
          disabled={submitted}
          onPress={() => respond(false)}
        />
      </View>
      {answerField}
      {errorText}
    </View>
  );
};

export const ToolFallback: ToolCallMessagePartComponent = ({
  toolName,
  argsText,
  status,
  approval,
  interrupt,
  addResult,
  resume,
  respondToApproval,
}) => {
  const isCancelled =
    status.type === "incomplete" && status.reason === "cancelled";
  const label =
    status.type === "running"
      ? `Running ${toolName}…`
      : status.type === "requires-action"
        ? `Waiting on ${toolName}`
        : status.type === "incomplete"
          ? `${isCancelled ? "Cancelled" : "Failed"} ${toolName}`
          : `Used ${toolName}`;
  const error =
    status.type === "incomplete" && status.error != null
      ? formatUnknownValue(status.error)
      : "";
  const shouldRenderApproval =
    status.type === "requires-action" &&
    offersInterruptAction(status, approval, interrupt);

  return (
    <View className="aui-tool-fallback-root border-border bg-card my-1 gap-2 rounded-xl border px-3 py-2">
      <View className="aui-tool-fallback-header flex-row items-center gap-2">
        <Icon as={WrenchIcon} className="text-muted-foreground size-4" />
        <Text className="aui-tool-fallback-title text-muted-foreground text-sm">
          {label}
        </Text>
      </View>
      {error !== "" && (
        <View className="aui-tool-fallback-error gap-0.5 ps-6">
          <Text className="text-muted-foreground text-xs font-semibold">
            {isCancelled ? "Cancelled reason:" : "Error:"}
          </Text>
          <Text className="text-muted-foreground text-xs" selectable>
            {error}
          </Text>
        </View>
      )}
      {(shouldRenderApproval || isSettled(approval)) && (
        <ToolFallbackApproval
          className="ps-6"
          argsText={argsText}
          status={status}
          approval={approval}
          interrupt={interrupt}
          addResult={addResult}
          resume={resume}
          respondToApproval={respondToApproval}
        />
      )}
    </View>
  );
};

// templates/nuxt/app/components/assistant-ui/tool-fallback.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch, watchEffect } from "vue";
import { useAui, useAuiState, type ToolUIProps } from "@assistant-ui/vue";
import {
  toolApprovalAcceptsText,
  type ToolApprovalAnswer,
  type ToolApprovalOption,
  type ToolApprovalQuestion,
} from "@assistant-ui/core";
import type {} from "@assistant-ui/core/store";
import {
  CollapsibleContent,
  CollapsibleRoot,
  CollapsibleTrigger,
} from "reka-ui";
import {
  AlertCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  CircleMinusIcon,
  LoaderIcon,
  XCircleIcon,
} from "@lucide/vue";

type Approval = NonNullable<ToolUIProps["part"]["approval"]>;

const APPROVED_RESULT = "Approved by user";
const DENIED_RESULT = "User denied tool execution";

const APPROVAL_OPTION_DEFAULT_LABELS: Record<string, string> = {
  "allow-once": "Allow",
  "allow-always": "Always allow",
  "reject-once": "Deny",
  "reject-always": "Always deny",
};

const isKnownKind = (kind: string) =>
  Object.hasOwn(APPROVAL_OPTION_DEFAULT_LABELS, kind);

const isAllowKind = (kind: string) =>
  kind === "allow-once" || kind === "allow-always";

const optionLabel = (option: ToolApprovalOption) =>
  option.label ??
  (isKnownKind(option.kind)
    ? APPROVAL_OPTION_DEFAULT_LABELS[option.kind]
    : undefined) ??
  option.id;

// A request that declares how it wants to be presented is asking a question,
// not gating an action, so a refusal is not one of the answers it accepts
// unless the request declares itself dismissible.
const isQuestion = (approval: Approval | undefined) =>
  approval?.display === "select" ||
  approval?.display === "text" ||
  approval?.display === "questions";

const isSettled = (approval: Approval | undefined) =>
  approval != null &&
  (approval.approved !== undefined || approval.resolution !== undefined);

const questionAcceptsText = (question: ToolApprovalQuestion) =>
  !question.options?.length || question.allowFreeform === true;

const formatUnknownValue = (value: unknown, space?: number): string => {
  if (typeof value === "string") return value;
  try {
    if (value instanceof Error) return String(value);
    const json = JSON.stringify(value, null, space);
    if (json !== undefined) return json;
  } catch {}
  try {
    return String(value);
  } catch {
    return "[Unserializable value]";
  }
};

const formatToolDuration = (ms: number) => {
  if (ms < 1000) return "<1s";
  const seconds = ms / 1000;
  if (seconds < 10) return `${(Math.floor(seconds * 10) / 10).toFixed(1)}s`;
  if (seconds < 60) return `${Math.floor(seconds)}s`;
  return `${Math.floor(seconds / 60)}m ${Math.floor(seconds % 60)}s`;
};

const button =
  "rounded-lg px-3 text-sm font-medium transition-[scale,background-color] active:scale-[0.98] disabled:pointer-events-none disabled:opacity-50";
const primary = "bg-primary text-primary-foreground hover:bg-primary/90";
const outline =
  "border-border bg-background hover:bg-accent hover:text-accent-foreground border";
const inline = "inline-flex items-center gap-1.5 py-1.5";
const primaryButton = [button, primary, inline];
const outlineButton = [button, outline, inline];
const textareaClass =
  "border-border bg-background placeholder:text-muted-foreground focus-visible:ring-ring/50 min-h-16 w-full resize-none rounded-lg border px-2.5 py-1.5 text-sm outline-none focus-visible:ring-2 disabled:opacity-50";

const aui = useAui();
const part = useAuiState((s) => (s.part.type === "tool-call" ? s.part : null));
const voiceActive = useAuiState((s) => s.thread.voice !== undefined);
const canAnswer = useAuiState((s) => s.thread.capabilities.answerToolCall);

const status = computed(() => part.value?.status);
const statusType = computed(() => status.value?.type ?? "complete");
const isRunning = computed(() => statusType.value === "running");
const isCancelled = computed(
  () =>
    status.value?.type === "incomplete" && status.value.reason === "cancelled",
);
const requiresAction = computed(() => statusType.value === "requires-action");

const label = computed(() => {
  switch (statusType.value) {
    case "running":
      return "Running tool";
    case "requires-action":
      return "Waiting on tool";
    case "incomplete":
      return `${isCancelled.value ? "Cancelled" : "Failed"} tool`;
    default:
      return "Used tool";
  }
});

const statusIcon = computed(() => {
  switch (statusType.value) {
    case "running":
      return LoaderIcon;
    case "requires-action":
      return AlertCircleIcon;
    case "incomplete":
      return XCircleIcon;
    default:
      return CheckIcon;
  }
});

const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
});
const now = ref<number | undefined>(undefined);
const timing = computed(() => part.value?.timing);
const clockRunning = computed(
  () =>
    timing.value !== undefined &&
    timing.value.completedAt === undefined &&
    isRunning.value,
);
watchEffect((onCleanup) => {
  if (!mounted.value || !clockRunning.value) return;
  now.value = Date.now();
  const id = setInterval(() => {
    now.value = Date.now();
  }, 1000);
  onCleanup(() => clearInterval(id));
});
const duration = computed(() => {
  const value = timing.value;
  if (value === undefined) return undefined;
  if (value.completedAt !== undefined)
    return formatToolDuration(Math.max(0, value.completedAt - value.startedAt));
  if (!clockRunning.value || now.value === undefined) return undefined;
  return formatToolDuration(Math.max(0, now.value - value.startedAt));
});

const open = ref(requiresAction.value);
watch(requiresAction, (value) => {
  if (value) open.value = true;
});

const errorText = computed(() => {
  const value = status.value;
  if (value?.type !== "incomplete") return null;
  if (value.error === undefined || value.error === null) return null;
  return formatUnknownValue(value.error) || null;
});

const approval = computed(() => part.value?.approval);
const interrupt = computed(() => part.value?.interrupt);
const offersInterruptAction = computed(() => {
  const value = status.value;
  return (
    value?.type !== "requires-action" ||
    value.reason !== "interrupt" ||
    approval.value != null ||
    interrupt.value != null
  );
});
const showApproval = computed(
  () =>
    (requiresAction.value && offersInterruptAction.value) ||
    isSettled(approval.value),
);

const receipt = computed(() => {
  const value = approval.value;
  if (value == null || !isSettled(value)) return null;
  if (value.resolution !== undefined)
    return {
      outcome: "closed" as const,
      label:
        value.resolution === "cancelled"
          ? "Cancelled before a decision"
          : "Expired before a decision",
      option: undefined,
    };
  const chosen =
    value.optionId === undefined
      ? undefined
      : value.options?.find((option) => option.id === value.optionId);
  const option = chosen !== undefined ? optionLabel(chosen) : value.optionId;
  const answered =
    isQuestion(value) || (chosen !== undefined && !isKnownKind(chosen.kind));
  const automatic = value.isAutomatic ? " automatically" : "";
  return value.approved
    ? {
        outcome: "allowed" as const,
        label: `${answered ? "Answered" : "Allowed"}${automatic}`,
        option,
      }
    : {
        outcome: "refused" as const,
        label: `${answered ? "Dismissed" : "Denied"}${automatic}`,
        option,
      };
});
const receiptIcon = computed(() => {
  switch (receipt.value?.outcome) {
    case "allowed":
      return CheckIcon;
    case "refused":
      return XCircleIcon;
    default:
      return CircleMinusIcon;
  }
});
const receiptAnswers = computed(() => {
  const value = approval.value;
  if (!value?.answers) return [];
  const answers = value.answers;
  return (value.questions ?? []).flatMap((question) => {
    const answer = Object.hasOwn(answers, question.id)
      ? answers[question.id]
      : undefined;
    const labels = [
      ...(answer?.optionIds ?? []).map(
        (id) =>
          question.options?.find((option) => option.id === id)?.label ?? id,
      ),
      ...(answer?.text?.trim() ? [answer.text] : []),
    ];
    return labels.length === 0
      ? []
      : [
          {
            id: question.id,
            title: question.header ?? question.prompt,
            labels: labels.join(", "),
          },
        ];
  });
});
const receiptNotes = computed(() => [
  ...new Set(
    [approval.value?.text, approval.value?.reason].filter(
      (value): value is string => typeof value === "string" && value !== "",
    ),
  ),
]);

const submitted = ref(false);
const locked = computed(() => submitted.value || voiceActive.value);
const confirmingId = ref<string | null>(null);
const answer = ref("");
const error = ref<string | null>(null);

const options = computed(() => approval.value?.options ?? []);
const allowOptions = computed(() =>
  options.value.filter((option) => isAllowKind(option.kind)),
);
const rejectOptions = computed(() =>
  options.value.filter(
    (option) => isKnownKind(option.kind) && !isAllowKind(option.kind),
  ),
);
const orderedOptions = computed(() => [
  ...allowOptions.value,
  ...options.value.filter((option) => !isKnownKind(option.kind)),
  ...rejectOptions.value,
]);
const question = computed(() => isQuestion(approval.value));
const dismissible = computed(
  () => question.value && approval.value?.dismissible === true,
);
const acceptsText = computed(
  () => approval.value != null && toolApprovalAcceptsText(approval.value),
);
const confirming = computed(() =>
  confirmingId.value == null
    ? undefined
    : options.value.find((option) => option.id === confirmingId.value),
);
const confirmMeta = computed(() =>
  typeof confirming.value?.confirm === "object"
    ? confirming.value.confirm
    : undefined,
);

// A refused response leaves the request open, so the controls come back
// rather than staying spent on a decision the runtime never recorded.
const submit = (send: () => Promise<void> | void) => {
  submitted.value = true;
  error.value = null;
  void (async () => {
    try {
      await send();
    } catch (sendError) {
      submitted.value = false;
      error.value =
        sendError instanceof Error ? sendError.message : String(sendError);
    }
  })();
};

const typedNote = () => (answer.value.trim() ? { text: answer.value } : {});

const respond = (approved: boolean) => {
  if (locked.value) return;
  const value = status.value;
  if (approval.value != null && approval.value.approved === undefined) {
    submit(() => aui.part.respondToToolApproval({ approved, ...typedNote() }));
  } else if (interrupt.value) {
    submit(() => aui.part.resumeToolCall({ approved }));
  } else if (
    value?.type === "requires-action" &&
    value.reason === "interrupt"
  ) {
    return;
  } else {
    submit(() =>
      aui.part.addToolResult(approved ? APPROVED_RESULT : DENIED_RESULT),
    );
  }
};

// A custom kind has no decision class for the runtime to derive, and
// responding without one throws; picking a declared option is an answer, so
// it resolves as approved.
const respondWithOption = (option: ToolApprovalOption) => {
  if (locked.value) return;
  confirmingId.value = null;
  submit(() =>
    aui.part.respondToToolApproval(
      isKnownKind(option.kind)
        ? { optionId: option.id, ...typedNote() }
        : { optionId: option.id, approved: true, ...typedNote() },
    ),
  );
};

const handleOption = (option: ToolApprovalOption) => {
  if (option.confirm) {
    confirmingId.value = option.id;
  } else {
    respondWithOption(option);
  }
};

const submitAnswer = () => {
  if (locked.value) return;
  submit(() => aui.part.respondToToolApproval({ text: answer.value }));
};

// A dismissal is no answer at all, so a typed draft does not travel with it.
const dismiss = () => {
  if (locked.value) return;
  submit(() => aui.part.respondToToolApproval({ approved: false }));
};

const questions = computed(() => approval.value?.questions ?? []);
const selected = ref<ReadonlyMap<string, readonly string[]>>(new Map());
const typed = ref<ReadonlyMap<string, string>>(new Map());

const isChosen = (item: ToolApprovalQuestion, optionId: string) =>
  (selected.value.get(item.id) ?? []).includes(optionId);
const isDescribed = (item: ToolApprovalQuestion) =>
  item.options?.some((option) => option.description) ?? false;
const toggle = (item: ToolApprovalQuestion, optionId: string) => {
  const chosen = selected.value.get(item.id) ?? [];
  const next = chosen.includes(optionId)
    ? chosen.filter((id) => id !== optionId)
    : item.multiple
      ? [...chosen, optionId]
      : [optionId];
  selected.value = new Map(selected.value).set(item.id, next);
};
const setTyped = (item: ToolApprovalQuestion, event: Event) => {
  const { value } = event.target as HTMLTextAreaElement;
  typed.value = new Map(typed.value).set(item.id, value);
};
const answerOf = (item: ToolApprovalQuestion): ToolApprovalAnswer => {
  const optionIds = selected.value.get(item.id) ?? [];
  const draft = typed.value.get(item.id);
  const text = draft?.trim() ? draft : undefined;
  return {
    ...(optionIds.length > 0 && { optionIds }),
    ...(text !== undefined && { text }),
  };
};
const questionsComplete = computed(
  () =>
    questions.value.length > 0 &&
    questions.value.every((item) => {
      const value = answerOf(item);
      return value.optionIds !== undefined || value.text !== undefined;
    }),
);
const sendAnswers = () => {
  if (locked.value || !questionsComplete.value) return;
  const answers = Object.fromEntries(
    questions.value.map((item) => [item.id, answerOf(item)]),
  );
  submit(() => aui.part.respondToToolApproval({ answers }));
};
</script>

<template>
  <CollapsibleRoot
    v-if="part"
    v-model:open="open"
    data-slot="aui_tool-fallback-root"
    class="w-full"
  >
    <CollapsibleTrigger
      data-slot="aui_tool-fallback-trigger"
      class="group/trigger text-muted-foreground hover:text-foreground flex w-fit origin-left items-center gap-2 py-1.5 text-sm transition-[color,scale] active:scale-[0.98]"
    >
      <component
        :is="statusIcon"
        class="size-4 shrink-0"
        :class="[
          isCancelled && 'text-muted-foreground',
          isRunning && 'animate-spin [animation-duration:0.6s]',
        ]"
      />
      <span
        class="inline-block text-start leading-none"
        :class="[
          isCancelled && 'text-muted-foreground line-through',
          isRunning && 'animate-pulse motion-reduce:animate-none',
        ]"
      >
        {{ label }}: <b>{{ part.toolName }}</b>
      </span>
      <span
        v-if="duration !== undefined"
        data-slot="aui_tool-fallback-duration"
        class="text-muted-foreground text-xs tabular-nums"
        >{{ duration }}</span
      >
      <ChevronDownIcon
        class="size-4 shrink-0 -rotate-90 transition-transform duration-200 ease-[cubic-bezier(0.32,0.72,0,1)] group-data-[state=open]/trigger:rotate-0 motion-reduce:transition-none"
      />
    </CollapsibleTrigger>
    <CollapsibleContent
      data-slot="aui_tool-fallback-content"
      class="aui-collapsible-content relative overflow-hidden text-sm outline-none"
    >
      <div class="flex flex-col gap-2 ps-6 pt-1 pb-2">
        <div v-if="errorText" data-slot="aui_tool-fallback-error">
          <p class="text-muted-foreground font-semibold">
            {{ isCancelled ? "Cancelled reason:" : "Error:" }}
          </p>
          <p class="text-muted-foreground whitespace-pre-line">
            {{ errorText }}
          </p>
        </div>
        <pre
          v-if="part.argsText"
          data-slot="aui_tool-fallback-args"
          class="bg-muted/50 text-foreground/90 rounded-md p-2.5 text-xs whitespace-pre-wrap"
          :class="isCancelled && 'opacity-60'"
          >{{ part.argsText }}</pre>
        <template v-if="showApproval">
          <div
            v-if="receipt"
            data-slot="aui_tool-fallback-approval-receipt"
            :data-outcome="receipt.outcome"
            class="flex flex-col gap-1.5 pt-1"
          >
            <p
              v-if="approval?.prompt"
              class="text-muted-foreground whitespace-pre-line"
            >
              {{ approval.prompt }}
            </p>
            <p class="flex items-center gap-1.5">
              <component
                :is="receiptIcon"
                aria-hidden="true"
                class="text-muted-foreground size-3.5 shrink-0"
              />
              <span class="font-medium">{{ receipt.label }}</span>
              <span
                v-if="receipt.option !== undefined"
                class="text-muted-foreground"
                >· {{ receipt.option }}</span
              >
            </p>
            <p
              v-for="row in receiptAnswers"
              :key="row.id"
              class="whitespace-pre-line"
            >
              <span class="text-muted-foreground">{{ row.title }}</span> ·
              {{ row.labels }}
            </p>
            <p
              v-for="note in receiptNotes"
              :key="note"
              class="text-muted-foreground whitespace-pre-line"
            >
              {{ note }}
            </p>
          </div>
          <template v-else-if="!canAnswer">
            <div
              v-if="approval?.prompt"
              data-slot="aui_tool-fallback-approval"
              class="flex flex-col gap-2 pt-1"
            >
              <p class="text-foreground whitespace-pre-line">
                {{ approval.prompt }}
              </p>
            </div>
          </template>
          <div
            v-else-if="confirming"
            data-slot="aui_tool-fallback-approval-confirm"
            class="flex flex-col gap-2 pt-1"
          >
            <p class="font-semibold">
              {{ confirmMeta?.title ?? `${optionLabel(confirming)}?` }}
            </p>
            <p
              v-if="confirmMeta?.description ?? confirming.description"
              class="text-muted-foreground whitespace-pre-line"
            >
              {{ confirmMeta?.description ?? confirming.description }}
            </p>
            <ul v-if="confirming.grants?.length" class="flex flex-col gap-1">
              <li v-for="grant in confirming.grants" :key="grant">
                <code class="bg-muted rounded px-1.5 py-0.5 text-xs">{{
                  grant
                }}</code>
              </li>
            </ul>
            <div class="flex items-center gap-2">
              <button
                type="button"
                :class="primaryButton"
                :disabled="locked"
                @click="respondWithOption(confirming)"
              >
                Confirm
              </button>
              <button
                type="button"
                :class="outlineButton"
                :disabled="locked"
                @click="confirmingId = null"
              >
                Back
              </button>
            </div>
          </div>
          <div
            v-else-if="approval?.display === 'questions'"
            data-slot="aui_tool-fallback-approval"
            class="flex flex-col gap-3 pt-1"
          >
            <p
              v-if="approval.prompt"
              class="text-foreground whitespace-pre-line"
            >
              {{ approval.prompt }}
            </p>
            <div
              v-for="item in questions"
              :key="item.id"
              role="group"
              :aria-label="item.prompt"
              data-slot="aui_tool-fallback-approval-question"
              class="flex flex-col gap-2"
            >
              <p class="text-foreground whitespace-pre-line">
                <span
                  v-if="item.header"
                  class="text-muted-foreground me-1.5 text-xs font-medium uppercase"
                  >{{ item.header }}</span
                >{{ item.prompt }}
              </p>
              <div
                v-if="item.options?.length"
                class="flex gap-2"
                :class="
                  isDescribed(item)
                    ? 'flex-col items-stretch'
                    : 'flex-wrap items-center'
                "
              >
                <button
                  v-for="option in item.options"
                  :key="option.id"
                  type="button"
                  :class="[
                    button,
                    isChosen(item, option.id) ? primary : outline,
                    isDescribed(item)
                      ? 'flex flex-col items-start gap-0.5 py-2 text-start whitespace-normal'
                      : inline,
                  ]"
                  :aria-pressed="isChosen(item, option.id)"
                  :disabled="locked"
                  @click="toggle(item, option.id)"
                >
                  <span>{{ option.label }}</span>
                  <span
                    v-if="option.description"
                    class="text-xs font-normal opacity-80"
                    >{{ option.description }}</span
                  >
                </button>
              </div>
              <textarea
                v-if="questionAcceptsText(item)"
                :value="typed.get(item.id) ?? ''"
                :disabled="locked"
                :aria-label="item.prompt"
                :placeholder="
                  item.options?.length
                    ? 'Or type an answer'
                    : 'Type your answer'
                "
                :class="textareaClass"
                @input="setTyped(item, $event)"
              />
            </div>
            <div class="flex items-center gap-2">
              <button
                type="button"
                :class="primaryButton"
                :disabled="locked || !questionsComplete"
                @click="sendAnswers"
              >
                Send
              </button>
              <button
                v-if="approval.dismissible === true"
                type="button"
                :class="outlineButton"
                :disabled="locked"
                @click="dismiss"
              >
                Dismiss
              </button>
            </div>
            <p
              v-if="error"
              role="alert"
              class="text-destructive text-xs whitespace-pre-line"
            >
              {{ error }}
            </p>
          </div>
          <div
            v-else
            data-slot="aui_tool-fallback-approval"
            class="flex flex-col gap-2 pt-1"
          >
            <p
              v-if="approval?.prompt"
              class="text-foreground whitespace-pre-line"
            >
              {{ approval.prompt }}
            </p>
            <div
              v-if="orderedOptions.length > 0"
              class="flex flex-wrap items-center gap-2"
            >
              <button
                v-for="option in orderedOptions"
                :key="option.id"
                type="button"
                :class="
                  option === allowOptions[0] ? primaryButton : outlineButton
                "
                :disabled="locked"
                @click="handleOption(option)"
              >
                {{ optionLabel(option) }}
              </button>
              <button
                v-if="rejectOptions.length === 0 && !question"
                type="button"
                :class="outlineButton"
                :disabled="locked"
                @click="respond(false)"
              >
                Deny
              </button>
              <button
                v-if="!acceptsText && dismissible"
                type="button"
                :class="outlineButton"
                :disabled="locked"
                @click="dismiss"
              >
                Dismiss
              </button>
            </div>
            <div v-else-if="!question" class="flex items-center gap-2">
              <button
                type="button"
                :class="primaryButton"
                :disabled="locked"
                @click="respond(true)"
              >
                Allow
              </button>
              <button
                type="button"
                :class="outlineButton"
                :disabled="locked"
                @click="respond(false)"
              >
                Deny
              </button>
            </div>
            <div v-if="acceptsText" class="flex flex-col items-start gap-2">
              <textarea
                v-model="answer"
                :disabled="locked"
                :aria-label="question ? (approval?.prompt ?? 'Answer') : 'Note'"
                :placeholder="
                  question ? 'Type your answer' : 'Add a note to your decision'
                "
                :class="textareaClass"
              />
              <div v-if="question" class="flex items-center gap-2">
                <button
                  type="button"
                  :class="primaryButton"
                  :disabled="locked"
                  @click="submitAnswer"
                >
                  Send
                </button>
                <button
                  v-if="dismissible"
                  type="button"
                  :class="outlineButton"
                  :disabled="locked"
                  @click="dismiss"
                >
                  Dismiss
                </button>
              </div>
            </div>
            <div
              v-else-if="question && orderedOptions.length === 0 && dismissible"
              class="flex items-center gap-2"
            >
              <button
                type="button"
                :class="outlineButton"
                :disabled="locked"
                @click="dismiss"
              >
                Dismiss
              </button>
            </div>
            <p
              v-if="error"
              role="alert"
              class="text-destructive text-xs whitespace-pre-line"
            >
              {{ error }}
            </p>
          </div>
        </template>
        <div
          v-if="part.result !== undefined"
          data-slot="aui_tool-fallback-result"
        >
          <p class="text-muted-foreground text-xs font-medium">Result:</p>
          <pre
            class="bg-muted/50 text-foreground/90 mt-1 rounded-md p-2.5 text-xs whitespace-pre-wrap"
            >{{ formatUnknownValue(part.result, 2) }}</pre>
        </div>
      </div>
    </CollapsibleContent>
  </CollapsibleRoot>
</template>

<style scoped>
.aui-collapsible-content[data-state="open"] {
  animation: aui-collapsible-down 200ms cubic-bezier(0.32, 0.72, 0, 1);
}
.aui-collapsible-content[data-state="closed"] {
  animation: aui-collapsible-up 200ms cubic-bezier(0.32, 0.72, 0, 1);
}
@media (prefers-reduced-motion: reduce) {
  .aui-collapsible-content[data-state] {
    animation: none;
  }
}
@keyframes aui-collapsible-down {
  from {
    height: 0;
  }
  to {
    height: var(--reka-collapsible-content-height);
  }
}
@keyframes aui-collapsible-up {
  from {
    height: var(--reka-collapsible-content-height);
  }
  to {
    height: 0;
  }
}
</style>
